general:
  kafka-topic:
    transactions: transactions

fraud:
  large-amount-threshold: 10000
  frequency-limit: 10
  frequency-window-limit: 10

services:
  account-service:
    url: http://account-service:8082
  transaction-service:
    url: http://transaction-service:8081

spring:
  application:
    name: fraudservice
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: fraud-group
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.financialapigateway.fraudservice.event.TransactionEvent
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  config:
    import: optional:file:.env.local[.properties]

server:
  port: 8083
